apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: {{ .Values.app.image }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-read
          mountPath: /app/data/read
        - name: data-write
          mountPath: /app/data/write
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: VAULT_SECRET_PATH
          value: "secret/data/myapp"
      volumes:
      - name: data-read
        emptyDir: {}
      - name: data-write
        emptyDir: {}